### PR TITLE
BREAKING: Refactor for initial release

### PR DESCRIPTION
**Pull request by mehalter**
As we prepare for the initial release of AstroVim we need to do some user configuration cleanup to improve the user experience.

**THIS WILL BE A BREAKING CHANGE**

## TODO

- [x] Finalize user `init.lua`/config directory structure
- [x] Make sure everything that can be configured is set up to be configured
- [x] Update `README` (Started, needs to be proofread and cleaned up if needed. Needs to be easily understandable)
- [x] Move some advanced configuration to `user_example/README`
  - [x] moving from `init.lua` -> split up `user/` files
  - [x] all the supported formats for user config table overrides: `function(table)...end` vs `{...}`
  - [x] potentially move some stuff from the current `README` to the advanced configuration
- [x] Add more details to the `user_example/init.lua` file with comments and details
- [x] More Testing

### CODE REVIEW

**Comment by mehalter** [comment]
Changes so far:

- `server-settings` -> `lsp.server-settings`
- `lsp_installer.on_attach_override` -> `lsp.on_attach`
- `lsp_installer.server_registration_override` -> `lsp.server_registration_override`
- `colorizer.filetype_opts` and `colorizer.default_opts` now match the normal setup call structure and is just `colorizer = { {}, {} }` where the two tables are the first and second parameters of the `setup` function

**Comment by mehalter** [comment]
Discussing new file structure for the user config folder. Current proposal is something like:

```
user
├── lsp
│   ├── on_attach.lua
│   └── server-settings
│       ├── texlab.lua
│       └── yamlls.lua
├── plugins
|   ├── init.lua
│   ├── bufferline.lua
│   ├── colorizer.lua
|   ├── nvim-tree.lua
|   ├── packer.lua
|   ├── symbols_outline.lua
|   ├── telescope.lua
|   ├── toggleterm.lua
|   ├── treesitter.lua
│   ├── which-key
|   |   ├── init.lua
|   |   └── mappings.lua
├── null-ls.lua
├── settings.lua
```

Where `plugins/init.lua` allows for adding plugins and modifying default plugins, and `plugins/X.lua` refers to the `X.setup(...)` call for setting up the given plugin
Still need to figure out what to do with `which-key/` since in this configuration `which-key/init.lua` is the `which-key.setup()` and `which-key/mappings.lua` refers to the `which-key.register()` call for the normal mode `<leader>` prefix

**Comment by bryant-the-coder** [comment]
i guess it's going to be like chad-astrovim :D

**Comment by bryant-the-coder** [comment]
@mehalter ping me in discord or here if you need help ;D

**Review by kabinspace — APPROVED** [review]

**Pull request merged**
