### PR TITLE
Fix: issue #28

### PR DESCRIPTION
**Pull request by srRyo**
### FIXED:

- [x] issue #28 

### Added:

- "For-loop" in "core/options.lua" to make it easier to add and modify options (can also be used in "user/settings.lua")

- "packer_compiled.lua" and the "/user" directory to the .gitignore file.

Note: I fully added the "user" directory, in case any user needs to create directories to keep their custom settings in order and this is not detected as a change.

### CODE REVIEW

**Comment by kabinspace** [comment]
I really appreciate your effort but here are some of the things I want to clear, [This](https://github.com/kabinspace/AstroVim/pull/29/commits/94e69c2a11c6d61287add4cbd79be9e52e7d93bd) change is not really necessary because it's better for the user to re-compile after an update. [Here](https://github.com/kabinspace/AstroVim/pull/29/commits/e2cf96082d28798f637a5c9c7be24bc903000134) I purposely avoided using loop because it was not really necessary and I wanted to make it simple. [Here](https://github.com/kabinspace/AstroVim/pull/29/commits/b7b8c9588bb90f04b1271a719695fa83e2dfdb9f) I am only letting `.lua` because AstroVim only uses lua for the most part. [Here](https://github.com/kabinspace/AstroVim/pull/29/commits/4a7a393ae9c6c4c37a7b5e97c09be666ed05c315) toggleterm is lazyloaded for better startup time. I've already given [solution](https://github.com/kabinspace/AstroVim/issues/15#issuecomment-1030742915) in case the user's don't want to lazy load the plugin.

**Comment by kabinspace** [comment]
On second thought, I think allowing users to have a directory does make sense indeed. [Here](https://github.com/kabinspace/AstroVim/pull/29/commits/b7b8c9588bb90f04b1271a719695fa83e2dfdb9f) can you please remove the blank space in line number 3 before I merge that.

**Comment by srRyo** [comment]
@kabinspace Of course, I have already removed the blank space.

**Comment by kabinspace** [comment]
Can you also remove the rest of the files except for [this](https://github.com/kabinspace/AstroVim/pull/29/commits/93f13b66f93d73272e5284d4c66808841d6b1355) one

**Comment by kabinspace** [comment]
@srRyo Looks like you are creating conflicts with the main branch. Can you close this pull request and make another one where you only commit the changes for .gitignore?

**Pull request closed without merging**
